PyAny_MainApp/flames_app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired

class FlamesForm(FlaskForm):  
  your_name = StringField("Your name",validators=[DataRequired()])
  crush_name = StringField("Crush's name",validators=[DataRequired()])
  submit = SubmitField("Matchmake!")

PyAny_MainApp/core/views.py
from flask import render_template, Blueprint, request
from PyAny_MainApp.models import BlogPost

core = Blueprint("core",__name__)

@core.route('/')
def index():
    page = request.args.get('page',1,type=int)
    blog_posts = BlogPost.query.order_by(BlogPost.timestamp.desc()).paginate(page=page,per_page=10)
    
    return render_template('index.html',blog_posts=blog_posts)

@core.route('/info')
def info():
    return render_template('info.html')

PyAny_MainApp/covid19_dailyreports/views.py
from flask import render_template, url_for, flash, request, Blueprint
import pandas as pd
from datetime import datetime
from PyAny_MainApp.covid19_dailyreports.forms import HealthChecklistForm

covid19_dailyreports = Blueprint('covid19_dailyreports',__name__)

# Submit online daily monitoring form
@covid19_dailyreports.route('/covid19_healthchecklistform',methods=['GET','POST'])
def covid19_healthchecklistform():
  #form = HealthChecklistForm()
  #if form.validate_on_submit:
  #  pass
  return render_template('covid19_healthchecklistform.html')

PyAny_MainApp/flames_app/views.py
from flask import render_template, Blueprint
from PyAny_MainApp.flames_app.forms import FlamesForm
from PyAny_MainApp.flames_app.flames_match import match_results

flames_app = Blueprint('flames_app',__name__)

# Submit online daily monitoring form
@flames_app.route('/flames_app', methods=['GET','POST'])
def flames():
  form = FlamesForm()
  results_header = "Results"
  results = "(Results display here)"
  if form.validate_on_submit:
    your_name = form.your_name.data
    crush_name = form.crush_name.data
    try:
      results_header = f"Results for {your_name.title()} and {crush_name.title()}"
      results = match_results(yourName=your_name,crushName=crush_name)
    except:
      results_header = "Results"
      results = "(Results display here)"
      return render_template('flames_app.html',form=form,results=results,results_header=results_header)
    return render_template('flames_app.html',form=form,results=results,results_header=results_header)
  
  return render_template('flames_app.html',form=form,results=results)

PyAny_MainApp/posts/views.py
from flask import render_template, url_for, flash, request, redirect, Blueprint, abort
from flask_login import current_user, login_required
from PyAny_MainApp import db
from PyAny_MainApp.models import BlogPost
from PyAny_MainApp.posts.forms import BlogPostForm
from datetime import datetime

blog_posts = Blueprint('blog_posts',__name__)

# Create Blog Post
@blog_posts.route('/create_post',methods=['GET','POST'])
@login_required
def create_post():
  form = BlogPostForm()
  username = current_user.username
  if form.validate_on_submit():
    blog_post = BlogPost( title = form.title.data,
                          text=form.text.data,
                          user_id=current_user.id,
                          timestamp=datetime.now(),
                          )
    db.session.add(blog_post)
    db.session.commit()
    flash('Blog post created!')
    return redirect(url_for('core.index'))

  return render_template('create_post.html',form=form,username=username)

# View(Read) Blog Post
@blog_posts.route('/<int:blog_post_id>')
def blog_post(blog_post_id):
  blog_post = BlogPost.query.get_or_404(blog_post_id)
  return render_template('blog_post.html',
                         title=blog_post.title,
                         timestamp=blog_post.timestamp,
                         post=blog_post
                        )

# Update Blog Post
@blog_posts.route('/<int:blog_post_id>/update_post',methods=['GET','POST'])
@login_required
def update_post(blog_post_id):
  blog_post = BlogPost.query.get_or_404(blog_post_id)

  if blog_post.author != current_user:
    abort(403)

  form = BlogPostForm()

  if form.validate_on_submit():
    blog_post.title = form.title.data
    blog_post.text = form.text.data
    db.session.commit()
    flash('Blog post updated!')
    return redirect(url_for('blog_posts.blog_post',blog_post_id=blog_post.id))

  elif request.method == 'GET':
    form.title.data = blog_post.title
    form.text.data = blog_post.text

  return render_template('create_post.html',
                         form=form,
                         title='Updating'
                         )

# Delete Blog Post
@blog_posts.route('/<int:blog_post_id>/delete_post',methods=['POST'])
@login_required
def delete_post(blog_post_id):
  blog_post = BlogPost.query.get_or_404(blog_post_id)

  if blog_post.author != current_user:
    abort(403)
  
  db.session.delete(blog_post)
  db.session.commit()
  flash('Blog post deleted!')
  return redirect(url_for('core.index'))

PyAny_MainApp/users/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required

from PyAny_MainApp import db
from PyAny_MainApp.models import User, BlogPost
from PyAny_MainApp.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from PyAny_MainApp.users.picture_handler import add_profile_pic

users = Blueprint('users',__name__)

# Register User
@users.route('/register',methods=['GET','POST'])
def register():
  form = RegistrationForm()

  if form.validate_on_submit():
    user = User(email=form.email.data,
                username=form.username.data,
                password=form.password.data
                )
    db.session.add(user)
    db.session.commit()
    flash('Registration complete!',)
    return redirect(url_for('users.login'))
  return render_template('register.html',form=form)

# Login User
@users.route('/login',methods=['GET','POST'])
def login():
  form = LoginForm()

  if form.validate_on_submit():
    user = User.query.filter_by(email=form.email.data).first()
    if user.check_password(form.password.data) and user is not None:
      login_user(user)
      flash('Login success!')
      next = request.args.get('next')

      if next == None or not next[0] == '/':
        next = url_for('core.index')
      return redirect(next)
  return render_template('login.html',form=form)

# Logout User
@users.route('/logout')
def logout():
  logout_user()
  return redirect(url_for("core.index"))

# Access/Update User Account
@users.route('/account',methods=['GET','POST'])
@login_required
def account():
  form = UpdateUserForm()
  
  if form.validate_on_submit():
    if form.picture.data:
      username = current_user.username
      pic = add_profile_pic(form.picture.data,username)
      current_user.profile_image = pic

    current_user.username = form.username.data
    current_user.email = form.email.data
    db.session.commit()
    flash('User account updated!')
    return redirect(url_for('users.account'))

  elif request.method == 'GET':
    form.username.data = current_user.username
    form.email.data = current_user.email

  profile_image = url_for('static',filename='profile_pics/'+current_user.profile_image)

  return render_template('account.html',profile_image=profile_image,form=form)

# User Blogposts
@users.route('/<username>')
def user_posts(username):
  page = request.args.get('page',1,type=int)
  user = User.query.filter_by(username=username).first_or_404()
  
  blog_posts = BlogPost.query.filter_by(author=user).order_by(BlogPost.timestamp.desc()).paginate(page=page,per_page=5)
  
  #blog_posts = BlogPost.query.filter_by(author=user)
  #blog_posts.order_by(BlogPost.timestamp.desc())
  #blog_posts.paginate(page=page,per_page=5)

  return render_template('user_blog_posts.html',blog_posts=blog_posts,user=user)

  

PyAny_MainApp/templates/account.html
{% extends 'base.html' %}

{% block title %}
User Account
{% endblock %}


{% block content %}
<div align='center' class="container jumbotron" style="width: 25rem;">
    <img align='center' src="{{ url_for('static',filename='profile_pics/'+current_user.profile_image) }}">
    <hr class="my-4">
    <h3 align='center' class="display-4">{{ current_user.username }}</h3>
</div>
<div class="container card" style="width: 25rem;">
  <hr class="my-4">
  <form method="POST" action="" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    <div class="form-group">
      {{ form.email.label }}
      {{ form.email(class_='form-control') }}
    </div>
    <div class="form-group">
      {{ form.username.label }}
      {{ form.username(class_='form-control') }}
    </div>
    <div class="form-group">
      {{ form.picture.label }}
      {{ form.picture(class_='form-control-file') }}
    </div>
    <div class="form-group">
    {{ form.submit(class_='btn btn-primary') }}
    </div>
  </form>
</div>
{% endblock %}

PyAny_MainApp/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    <title>
      {% block title %}
      {% endblock %}
    </title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{{ url_for('core.index') }}">jaupy</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{{ url_for('core.index') }}">Home <span class="sr-only">(current)</span></a>
          </li>
          {% if current_user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link active" href="{{ url_for('users.logout') }}">Logout</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{{ url_for('users.account') }}">Account</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Do Something
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{{ url_for('blog_posts.create_post') }}">Create Post</a>
              <a class="dropdown-item" href="{{ url_for('flames_app.flames') }}">F.L.A.M.E.S. Match!</a>
            </div>
          {% else %}
          <li class="nav-item">
            <a class="nav-link active" href="{{ url_for('users.login') }}">Login</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Do Something
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <!--
              <a class="dropdown-item" href="{{ url_for('users.register') }}">Register</a>              
              <a class="dropdown-item" href="{{ url_for('covid19_dailyreports.covid19_healthchecklistform') }}">COVID-19 Daily Health Monitoring</a>
              <a class="dropdown-item" href="#">DMA Data Analyzer</a>
              -->
              <a class="dropdown-item" href="{{ url_for('flames_app.flames') }}">F.L.A.M.E.S. Match!</a>
            </div>
          </li
          {% endif %}
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{{ url_for('core.info') }}" tabindex="-1" aria-disabled="true">About</a>
          </li>
        </ul>
        <!-- Search Form --><!--
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
        -->
      </div>
    </nav>
    {% block content %}
    {% endblock %}
  </body>
</html>

PyAny_MainApp/templates/blog_post.html
{% extends 'base.html' %}

{% block title %}
Blogs
{% endblock %}


{% block content %}
<div class="container jumbotron" style="width: 50rem;">
  <h3 class="display-6">{{ title }}</h3>
  <hr class="my-4">
  <small class="card-subtitle mb-2">
    Posted by: {{ post.author.username }}
    <p class="text-muted">
    {{ timestamp.strftime("%B %d, %Y %I:%M:%S %p") }} UTC</p>
  </small>
  <p class="card-text">
    {{ post.text }}
  </p>
  {% if post.author == current_user %}
  <div class="container">
      <a class="btn btn-secondary" href="{{ url_for('blog_posts.update_post',blog_post_id=post.id) }}">Update</a>
      <button type="button" class="btn btn-danger" data-toggle='modal' data-target="#del_modal">Delete</button>
  </div>
  {% endif %}
  <!--Modal Section-->
  <div class="modal" tabindex="-1" role="dialog" id="del_modal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Delete Confirmation</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete this blog post?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>          
          <form action="{{ url_for('blog_posts.delete_post',blog_post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" name="" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

PyAny_MainApp/templates/covid19_healthchecklistform.html
{% extends 'base.html' %}

{% block title %}
  COVID-19 Daily Health Monitoring Form
{% endblock %}

{% block content %}
<div class="container card" style="width: 25rem;">
	<hr class="my-4">
	<h3 align="center" class="card-title">Daily Health Checklist</h3>
	<hr class="my-4">
	<form method="POST">

		<div class="form-group">
			<input type="text" class="form-control" placeholder="Full Name">
		</div>
    <div class="form-group">
      <textarea class="form-control" rows="3" placeholder="Full Address Here"></textarea>
    </div>
    <div class="form-group">
      <div class="form-row">
        <div class="col">
          <select class="form-control">
            <option selected>Gender</option>
            <option>Male</option>
            <option>Female</option>
          </select>
        </div>
      </div>
    </div>
    <div class="form-group">
      <button class="btn btn-primary" type="submit">Submit form</button>
    </div>
  </form>
</div>
{% endblock %}

PyAny_MainApp/templates/create_post.html
{% extends 'base.html' %}

{% block title %}
Create Blogpost
{% endblock %}


{% block content %}
<div class="container jumbotron" style="width: 50rem;">
    <h3 class="display-6">Compose Blog</h3>
    <hr class="my-4">
</div>
<div class="container jumbotron card" style="width: 50rem;">
  <form method="POST">
    {{ form.hidden_tag() }}
    
    <div class="form-group">
      <!--{{ form.title.label(class_="form-control-label") }}-->
      {{ form.title(class_='form-control',value="[Enter Title Here]") }}
    </div>
    
    <div class="form-group">
      <!--{{ form.text.label(class_="form-control-label") }}-->
      <small>Compose Blog</small>
      {{ form.text(class_='form-control',value="[Compose blog here]") }}
    </div>
    <div class="form-group">
    {{ form.submit(class_='btn btn-outline-info') }}
    </div>
  </form>
</div>
{% endblock %}

PyAny_MainApp/templates/flames_app.html
{% extends 'base.html' %}

{% block title %}
  F.L.A.M.E.S. Matchmaking App
{% endblock %}

{% block content %}
<div class="container card" style="width: 25rem;">
	<hr class="my-4">
	<h3 align="center" class="card-title">F.L.A.M.E.S. Match!</h3>
	<h5 align="center" class="card-title">The Tinder of 90's kids</h5>
  <hr class="my-4">
  <small class="card-text">Try to experiment using full names or just first names for different results so that hope is not all gone!</small>
  <hr class="my-4">
	<form method="POST">
    {{ form.hidden_tag() }}
		<div class="form-group">
      {{ form.your_name(class_='form-control',value="Your Name") }}
			<!--<input type="text" class="form-control" placeholder="Your Name">-->
		</div>
		<div class="form-group">
      {{ form.crush_name(class_='form-control',value="Crush's Name") }}
      <!--<input type="text" class="form-control" placeholder="Crush's Name">-->
		</div>
    <div class="form-group">
      {{ form.submit(class_='btn btn-danger') }}
      <!--<button class="btn btn-primary" type="submit">Matchmake!</button>-->
    </div>
  </form>
  <div class="card" method="GET">
    <div class="card-header">
      {{ results_header }}
    </div>
    <div class="card-body">
      <blockquote class="blockquote mb-0">
        <p>{{ results }}</p>
      </blockquote>
    </div>
</div>
</div>
{% endblock %}

PyAny_MainApp/templates/index.html
{% extends 'base.html' %}

{% block title %}
Home Page
{% endblock %}


{% block content %}
<div class="container jumbotron">
  <h3 class="display-6">Freedom Blogs!</h3>
  <p class="lead">This is a simple website that allows text-only blogs for users.</p>
  <hr class="my-4">
  <p>Enjoy the simplicity.</p>
</div>
<div class="container">
  {% for post in blog_posts.items %}
  <div class="card" style="width: 25rem;">
    <div class="card-body">
      <h5 class="card-title">
        <a href="{{ url_for('blog_posts.blog_post',blog_post_id=post.id) }}">{{ post.title }}</a>
      </h5>
      <h6 class="card-subtitle mb-2 text-muted">
        by <a href="{{ url_for('users.user_posts',username=post.author.username) }}">{{ post.author.username }}</a> | 
        <small>{{ post.timestamp.strftime("%B %d, %Y, %-I:%M:%S %p") }}</small><small> UTC </small>
      </h6>
      <p class="card-text">{{ post.text }}</p>
      <a href="{{ url_for('blog_posts.blog_post',blog_post_id=post.id) }}" class="btn btn-primary">Read / Edit</a>
    </div>
    <div class="card-footer"></div>
  </div>
  
  {% endfor %}
</div>
<!--Pagination Section-->
<div class="container">
  <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
      {% for page_num in blog_posts.iter_pages(left_edge=1,
                                               right_edge=1,
                                               left_current=1,
                                               right_current=2) %}
        {% if blog_posts.page == page_num %}
          <li class="page-item disabled">
            <a class="page-link" href="{{url_for('core.index',page=page_num)}}">
              {{ page_num }}
            </a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="{{url_for('core.index',page=page_num)}}">
              {{ page_num }}
            </a>
          </li>
        {% endif %}
      {% endfor %}
    </ul>
  </nav>
</div>
{% endblock %}

PyAny_MainApp/templates/info.html
{% extends 'base.html' %}

{% block title %}
About Page
{% endblock %}


{% block content %}
<div class="container jumbotron">
  <h1 class="display-4"><small>About jaupy</small></h1>
      <p class="lead">
        This is test website I made using the a Python web framework Flask. This whole thing doesn't do much for now. But I hope an idea pops up someday.
      </p>
  <hr class="my-4">
  <p>We all have to start somewhere somehow.<br>
    "The most necessary step in learning how to swim is to be in water."</p>
</div>
{% endblock %}

PyAny_MainApp/templates/login.html
{% extends 'base.html' %}

{% block title %}
Login
{% endblock %}


{% block content %}
<div class="container card" style="width: 25rem;">
  <hr class="my-4">
  <h3 align="center" class="card-title">Login</h3>
  <hr class="my-4">
  <form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
      {{ form.email.label }}{{ form.email(class_='form-control') }}
    </div>
    <div class="form-group">
      {{ form.password.label }}{{ form.password(class_='form-control') }}
    </div>
    <div class="form-group">
    {{ form.submit(class_='btn btn-primary') }}
    </div>
  </form>
</div>
{% endblock %}

PyAny_MainApp/templates/register.html
{% extends 'base.html' %}

{% block title %}
Registration
{% endblock %}


{% block content %}
<div class="container card" style="width: 25rem;">
  <hr class="my-4">
  <h3 align="center" class="card-title">Registration Page</h3>
  <hr class="my-4">
  <form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
      {{ form.email.label }}{{ form.email(class_='form-control') }}
      <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>
    <div class="form-group">
      {{ form.username.label }}{{ form.username(class_='form-control') }}
      <small id="emailHelp" class="form-text text-muted">Subject for verification. Chosen Username must be unique.</small>
    </div>
    <div class="form-group">
      {{ form.password.label }}{{ form.password(class_='form-control') }}
    </div>
    <div class="form-group">
      {{ form.pass_confirm.label }}{{ form.pass_confirm(class_='form-control') }}
    </div>
    <div class="form-group">
    {{ form.submit(class_='btn btn-primary') }}
    </div>
  </form>
</div>
{% endblock %}

PyAny_MainApp/templates/user_blog_posts.html
{% extends 'base.html' %}

{% block title %}
User Blogs
{% endblock %}

{% block content %}
<!--Blogs Header-->
<div class="container jumbotron">
  <h3 class="display-6">{{ user.username }} Blogs</h3>
  <hr class="my-4">
  <img align='center' src="{{ url_for('static',filename='profile_pics/'+user.profile_image) }}">
</div>
<!--Blogs Section-->
{% for post in blog_posts.items %}
<div class="container card w-75">
  <div class="card-body">
    <h5 class="card-title">
      <a href="{{ url_for('blog_posts.blog_post',blog_post_id=post.id) }}">
        Read Full
      </a>
    </h5>
    <small class="card-subtitle mb-2">
      Posted by: <a href="{{url_for('users.user_posts',username=post.author.username)}}">
                  {{ post.author.username }}
                 </a>
      | <p class="text-muted">
        {{ post.timestamp.strftime("%B %d, %Y, %-I:%M:%S %p") }} UTC</p>
    </small>
    <p class="card-text">
      {{ post.text }}
    </p>
  </div>
</div>
{% endfor %}
<!--Pagination Section-->
<div class="container">
  <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
      {% for page_num in blog_posts.iter_pages(left_edge=1,
                                               right_edge=1,
                                               left_current=1,
                                               right_current=2) %}
        {% if blog_posts.page == page_num %}
          <li class="page-item disabled">
            <a class="page-link" href="{{url_for('users.user_posts',username=user.username,page=page_num)}}">
              {{ page_num }}
            </a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="{{url_for('users.user_posts',username=user.username,page=page_num)}}">
              {{ page_num }}
            </a>
          </li>
        {% endif %}
      {% endfor %}
    </ul>
  </nav>
</div>
{% endblock %}